// src/components/Chatbot.jsx
import React, { useState, useRef, useEffect } from 'react';

const Chatbot = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // API call to Vercel backend (serverless function)
  const callBackendAPI = async (userMessage, conversationHistory = [], retryCount = 0) => {
    try {
      // Prepare conversation history for context (last 10 messages)
      const history = conversationHistory.slice(-10).map(msg => ({
        role: msg.sender === 'user' ? 'user' : 'assistant',
        content: msg.text
      }));
      
      // Add current message
      history.push({ role: 'user', content: userMessage });

      // Use relative path for Vercel - this will call /api/chat
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messages: history
        })
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'API request failed');
      }

      const data = await response.json();
      
      // Log if Gemini was used (for debugging)
      if (data.usedGemini) {
        console.log('✨ Response generated by Gemini AI');
      } else {
        console.log('📝 Response generated by fallback system');
      }
      
      return data.content;
    } catch (error) {
      console.error('Backend Error:', error);
      
      // Retry once if failed
      if (retryCount === 0) {
        console.log('🔄 Retrying request...');
        await new Promise(resolve => setTimeout(resolve, 1000));
        return callBackendAPI(userMessage, conversationHistory, 1);
      }
      
      throw error;
    }
  };

  // Initialize welcome message
  useEffect(() => {
    if (isOpen && messages.length === 0) {
      setMessages([
        {
          id: Date.now(),
          text: "👋 Hi! I'm **WolfrasAI**, your intelligent assistant powered by **Gemini AI**.\n\nI can answer questions about:\n\n• 📚 **Mugisha Isihaqa (wolfras)** - Full-Stack Developer\n• 💼 **Projects** and work experience\n• 💻 **Web development** technologies\n• 🌍 **General knowledge** (capitals, history, science)\n• 📧 **Contact information**\n\nWhat would you like to know today? 🐺",
          sender: 'ai',
          timestamp: new Date()
        }
      ]);
    }
  }, [isOpen, messages.length]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    // Add user message
    const userMessage = {
      id: Date.now(),
      text: input,
      sender: 'user',
      timestamp: new Date()
    };
    setMessages(prev => [...prev, userMessage]);
    const currentInput = input;
    setInput('');
    setIsLoading(true);

    try {
      // Call backend with conversation history for context
      const aiResponse = await callBackendAPI(currentInput, messages);
      
      const aiMessage = {
        id: Date.now() + 1,
        text: aiResponse,
        sender: 'ai',
        timestamp: new Date()
      };
      setMessages(prev => [...prev, aiMessage]);
    } catch (error) {
      console.error('AI Error:', error);
      const errorMessage = {
        id: Date.now() + 1,
        text: "⚠️ I'm having trouble connecting to my AI brain. Please try again in a moment.\n\nIf this issue persists, you can reach out directly at: **wolfras87@gmail.com**",
        sender: 'ai',
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  // Typing indicator component
  const TypingIndicator = () => (
    <div className="chat-message ai">
      <div className="message-header">
        <strong>WolfrasAI</strong>
      </div>
      <div className="typing-indicator">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  );

  if (!isOpen) {
    return (
      <button className="chatbot-toggle" onClick={() => setIsOpen(true)}>
        💬
      </button>
    );
  }

  return (
    <div className="chatbot">
      <div className="chatbot-header">
        <div>
          <h4>🤖 WolfrasAI</h4>
          <small>Powered by Gemini AI</small>
        </div>
        <button onClick={() => setIsOpen(false)} className="close-btn">
          ×
        </button>
      </div>
      
      <div className="chatbot-messages">
        {messages.map((msg) => (
          <div key={msg.id} className={`chat-message ${msg.sender}`}>
            <div className="message-header">
              <strong>{msg.sender === 'user' ? 'You' : 'WolfrasAI'}</strong>
              <small>{msg.timestamp.toLocaleTimeString()}</small>
            </div>
            <p style={{ whiteSpace: 'pre-wrap', lineHeight: '1.5' }}>
              {msg.text}
            </p>
          </div>
        ))}
        
        {isLoading && <TypingIndicator />}
        <div ref={messagesEndRef} />
      </div>
      
      <form onSubmit={handleSubmit} className="chatbot-input">
        <input
          type="text"
          placeholder="Ask me anything about wolfras or web development..."
          value={input}
          onChange={(e) => setInput(e.target.value)}
          disabled={isLoading}
          onKeyPress={(e) => e.key === 'Enter' && handleSubmit(e)}
        />
        <button type="submit" disabled={isLoading}>
          {isLoading ? '...' : 'Send'}
        </button>
      </form>
    </div>
  );
};

export default Chatbot;